CC=gcc
CFLAGS=-Wall -c -o
LDFLAGS=
all : editeur warcraft
editeur : editeur.o video.o perso.o
	$(CC) -o $@ $^
editeur.o : editeur.c editeur.h video.h perso.h
	$(CC) $(CFLAGS) $@ $<
perso.o : perso.c perso.h video.h
	$(CC) $(CFLAGS) $@ $<
video.o : video.c video.h
	$(CC) $(CFLAGS) $@ $<
warcraft : warcraft.o video.o perso.o
	$(CC) -o $@ $^
warcraft.o : warcraft.c warcraft.h video.h perso.h
	$(CC) $(CFLAGS) $@ $< 
clean:
	rm -f *.o editeur warcraft
